/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { HTTPValidationError } from '../models';
import { MarketplaceSummary } from '../models';
/**
 * DashboardApi - axios parameter creator
 * @export
 */
export const DashboardApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Marketplace Inventory
         * @param {any} marketplace 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        marketplaceInventoryDashboardInventoryGet: async (marketplace: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'marketplace' is not null or undefined
            if (marketplace === null || marketplace === undefined) {
                throw new RequiredError('marketplace','Required parameter marketplace was null or undefined when calling marketplaceInventoryDashboardInventoryGet.');
            }
            const localVarPath = `/dashboard/inventory/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (marketplace !== undefined) {
                localVarQueryParameter['marketplace'] = marketplace;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DashboardApi - functional programming interface
 * @export
 */
export const DashboardApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Marketplace Inventory
         * @param {any} marketplace 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async marketplaceInventoryDashboardInventoryGet(marketplace: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<MarketplaceSummary>>> {
            const localVarAxiosArgs = await DashboardApiAxiosParamCreator(configuration).marketplaceInventoryDashboardInventoryGet(marketplace, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DashboardApi - factory interface
 * @export
 */
export const DashboardApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Marketplace Inventory
         * @param {any} marketplace 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async marketplaceInventoryDashboardInventoryGet(marketplace: any, options?: AxiosRequestConfig): Promise<AxiosResponse<MarketplaceSummary>> {
            return DashboardApiFp(configuration).marketplaceInventoryDashboardInventoryGet(marketplace, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DashboardApi - object-oriented interface
 * @export
 * @class DashboardApi
 * @extends {BaseAPI}
 */
export class DashboardApi extends BaseAPI {
    /**
     * 
     * @summary Marketplace Inventory
     * @param {any} marketplace 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public async marketplaceInventoryDashboardInventoryGet(marketplace: any, options?: AxiosRequestConfig) : Promise<AxiosResponse<MarketplaceSummary>> {
        return DashboardApiFp(this.configuration).marketplaceInventoryDashboardInventoryGet(marketplace, options).then((request) => request(this.axios, this.basePath));
    }
}
