/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BodyOfferwallSoftpairPostProductIdOfferwall37d1da64OfferwallIdPost
 */
export interface BodyOfferwallSoftpairPostProductIdOfferwall37d1da64OfferwallIdPost {

    /**
     * @type {any}
     * @memberof BodyOfferwallSoftpairPostProductIdOfferwall37d1da64OfferwallIdPost
     */
    answers: any;
}
