/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * This represents one of the \"tasks\" within a bucket's ordered list of tasks.
 *
 * @export
 * @interface BucketTask
 */
export interface BucketTask {

    /**
     * The internal task id for this task within the marketplace
     *
     * @type {any}
     * @memberof BucketTask
     */
    id: any;

    /**
     * The namespaced task id for this task within the marketplace
     *
     * @type {any}
     * @memberof BucketTask
     */
    idCode: any;

    /**
     * @type {any}
     * @memberof BucketTask
     */
    source: any;

    /**
     * expected loi in seconds
     *
     * @type {any}
     * @memberof BucketTask
     */
    loi: any;

    /**
     * integer cents
     *
     * @type {any}
     * @memberof BucketTask
     */
    payout: any;
}
