/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CashoutMethodForeignValue } from './cashout-method-foreign-value';
 /**
 * 
 *
 * @export
 * @interface CashoutMethodForeignValueResponse
 */
export interface CashoutMethodForeignValueResponse {

    /**
     * The status of the API response.
     *
     * @type {any}
     * @memberof CashoutMethodForeignValueResponse
     */
    status: any;

    /**
     * An optional message, if the status is error.
     *
     * @type {any}
     * @memberof CashoutMethodForeignValueResponse
     */
    msg?: any;

    /**
     * @type {CashoutMethodForeignValue}
     * @memberof CashoutMethodForeignValueResponse
     */
    cashoutMethodValue: CashoutMethodForeignValue;
}
