/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CashoutMethodOut
 */
export interface CashoutMethodOut {

    /**
     * Unique ID for this cashout method
     *
     * @type {any}
     * @memberof CashoutMethodOut
     */
    id: any;

    /**
     * The currency of the cashout. Only USD is supported.
     *
     * @type {any}
     * @memberof CashoutMethodOut
     */
    currency?: any;

    /**
     * The base currency of the money paid out. This is used for e.g. sending an Amazon UK gift card
     *
     * @type {any}
     * @memberof CashoutMethodOut
     */
    originalCurrency?: any;

    /**
     * @type {any}
     * @memberof CashoutMethodOut
     */
    data: any;

    /**
     * The description of the cashout method.
     *
     * @type {any}
     * @memberof CashoutMethodOut
     */
    description: any;

    /**
     * Link to an image to display
     *
     * @type {any}
     * @memberof CashoutMethodOut
     */
    imageUrl?: any;

    /**
     * (USD cents) The maximum amount that can be cashed out in one transaction.
     *
     * @type {any}
     * @memberof CashoutMethodOut
     */
    maxValue: any;

    /**
     * (USD cents) The minimum amount that can be cashed out in one transaction.
     *
     * @type {any}
     * @memberof CashoutMethodOut
     */
    minValue: any;

    /**
     * A descriptive name for the cashout method.
     *
     * @type {any}
     * @memberof CashoutMethodOut
     */
    name: any;

    /**
     * The method in which the requested payout is delivered.  Allowed values:   - __PAYPAL__ *(PAYPAL)*: User is paid out to their personal PayPal email address  - __TANGO__ *(TANGO)*: User is paid uut via a Tango Gift Card  - __dwolla__ *(DWOLLA)*: DWOLLA  - __ACH__ *(ACH)*: A payment is made to a bank account using ACH  - __CASH_IN_MAIL__ *(CASH_IN_MAIL)*: A payment is made in cash and mailed to the user.  - __PRIZE__ *(PRIZE)*: A payment is made as a prize with some monetary value  - __AMT__ *(AMT)*: This is used to designate either AMT_BONUS or AMT_HIT  - __amt_bonus__ *(AMT_BONUS)*: Amazon Mechanical Turk as a Bonus  - __amt_assignment__ *(AMT_HIT)*: Amazon Mechanical Turk for a HIT
     *
     * @type {any}
     * @memberof CashoutMethodOut
     */
    type: any;

    /**
     * An external ID. Can be shown to a user to disambiguate a user'spossibly multiple methods
     *
     * @type {any}
     * @memberof CashoutMethodOut
     */
    extId?: any;

    /**
     * @type {any}
     * @memberof CashoutMethodOut
     */
    productId?: any;

    /**
     * A unique identifier for each user, which is set by the Supplier. It should not contain any sensitive informationlike email or names, and should avoid using anyincrementing values.
     *
     * @type {any}
     * @memberof CashoutMethodOut
     */
    productUserId?: any;
}
