/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CashoutRequestInfo } from './cashout-request-info';
 /**
 * 
 *
 * @export
 * @interface CashoutRequestResponse
 */
export interface CashoutRequestResponse {

    /**
     * The status of the API response.
     *
     * @type {any}
     * @memberof CashoutRequestResponse
     */
    status: any;

    /**
     * An optional message, if the status is error.
     *
     * @type {any}
     * @memberof CashoutRequestResponse
     */
    msg?: any;

    /**
     * @type {CashoutRequestInfo}
     * @memberof CashoutRequestResponse
     */
    cashout: CashoutRequestInfo;
}
