/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Shows the expected value of a redemption in a foreign currency.
 *
 * @export
 * @interface CashoutMethodForeignValue
 */
export interface CashoutMethodForeignValue {

    /**
     * Value of the redemption in the currency's smallest unit.
     *
     * @type {any}
     * @memberof CashoutMethodForeignValue
     */
    value: any;

    /**
     * Supported Currencies for Foreign Redemptions  Allowed values:   - __USD__ *(USD)*: US Dollars. Smallest Unit: Cents.  - __CAD__ *(CAD)*: Canadian Dollars. Smallest Unit: Cents.  - __GBP__ *(GBP)*: British Pounds. Smallest Unit: Pence.  - __EUR__ *(EUR)*: Euros. Smallest Unit: Cents.  - __INR__ *(INR)*: Indian Rupees. Smallest Unit: Paise.  - __AUD__ *(AUD)*: Australian Dollars. Smallest Unit: Cents.  - __PLN__ *(PLN)*: Polish Zloty. Smallest Unit: Grosz.  - __SEK__ *(SEK)*: Swedish Krona. Smallest Unit: Öre.  - __SGD__ *(SGD)*: Singapore Dollars. Smallest Unit: Cents.  - __MXN__ *(MXN)*: Mexican Pesos. Smallest Unit: Centavos.
     *
     * @type {any}
     * @memberof CashoutMethodForeignValue
     */
    currency: any;

    /**
     * A string representation of the value in the currency.
     *
     * @type {any}
     * @memberof CashoutMethodForeignValue
     */
    valueString: any;
}
