/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * See models.thl.payout: PayoutEvent. We've confused a Cashout and a Payout. This is used only in the API response.
 *
 * @export
 * @interface CashoutRequestInfo
 */
export interface CashoutRequestInfo {

    /**
     * Unique ID for this cashout. This may be NULL if the status is REJECTED or FAILED, which may happen if the request is invalid.
     *
     * @type {any}
     * @memberof CashoutRequestInfo
     */
    id: any;

    /**
     * This is the name of the cashout method.
     *
     * @type {any}
     * @memberof CashoutRequestInfo
     */
    description: any;

    /**
     * @type {any}
     * @memberof CashoutRequestInfo
     */
    message?: any;

    /**
     *  - `PENDING` = PENDING  - `APPROVED` = APPROVED  - `REJECTED` = REJECTED  - `CANCELLED` = CANCELLED  - `FAILED` = FAILED  - `COMPLETE` = COMPLETE
     *
     * @type {any}
     * @memberof CashoutRequestInfo
     */
    status?: any;

    /**
     * @type {any}
     * @memberof CashoutRequestInfo
     */
    transactionInfo?: any;
}
