/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Category
 */
export interface Category {

    /**
     * @type {any}
     * @memberof Category
     */
    id: any;

    /**
     * @type {any}
     * @memberof Category
     */
    adwordsVerticalId?: any;

    /**
     * @type {any}
     * @memberof Category
     */
    label: any;

    /**
     * @type {any}
     * @memberof Category
     */
    path: any;

    /**
     * @type {any}
     * @memberof Category
     */
    parentId?: any;
}
