/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Used in an offerwall. Stores the association between a category and a bucket, with a score.
 *
 * @export
 * @interface CategoryAssociation
 */
export interface CategoryAssociation {

    /**
     * The category ID
     *
     * @type {any}
     * @memberof CategoryAssociation
     */
    id: any;

    /**
     * The category label
     *
     * @type {any}
     * @memberof CategoryAssociation
     */
    label: any;

    /**
     * @type {any}
     * @memberof CategoryAssociation
     */
    adwordsId?: any;

    /**
     * @type {any}
     * @memberof CategoryAssociation
     */
    adwordsLabel?: any;

    /**
     * The strength of the association of this bucketwith this category. Will sum to 1 within a bucket.
     *
     * @type {any}
     * @memberof CategoryAssociation
     */
    p: any;
}
