/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreatePayPalCashoutMethodRequest
 */
export interface CreatePayPalCashoutMethodRequest {

    /**
     * (product_user_id) The user to create this cashout method for.
     *
     * @type {any}
     * @memberof CreatePayPalCashoutMethodRequest
     */
    bpuid: any;

    /**
     * @type {any}
     * @memberof CreatePayPalCashoutMethodRequest
     */
    type?: any;

    /**
     * Email address of the paypal user
     *
     * @type {any}
     * @memberof CreatePayPalCashoutMethodRequest
     */
    email: any;
}
