/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateCashoutRequest
 */
export interface CreateCashoutRequest {

    /**
     * (product_user_id) The user requesting a cashout.
     *
     * @type {any}
     * @memberof CreateCashoutRequest
     */
    bpuid: any;

    /**
     * (USD cents) The amount requested for the cashout.
     *
     * @type {any}
     * @memberof CreateCashoutRequest
     */
    amount: any;

    /**
     * Unique ID for the cashout method the cashout is being requested with.
     *
     * @type {any}
     * @memberof CreateCashoutRequest
     */
    cashoutMethodId: any;
}
