/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Durations are in integer seconds. Describes the statistical distribution of expected durations of tasks within this bucket.
 *
 * @export
 * @interface DurationSummary
 */
export interface DurationSummary {

    /**
     * @type {any}
     * @memberof DurationSummary
     */
    min: any;

    /**
     * @type {any}
     * @memberof DurationSummary
     */
    max: any;

    /**
     * @type {any}
     * @memberof DurationSummary
     */
    mean?: any;

    /**
     * @type {any}
     * @memberof DurationSummary
     */
    q1: any;

    /**
     * @type {any}
     * @memberof DurationSummary
     */
    q2: any;

    /**
     * @type {any}
     * @memberof DurationSummary
     */
    q3: any;

    /**
     * @type {any}
     * @memberof DurationSummary
     */
    lowerWhisker: any;

    /**
     * @type {any}
     * @memberof DurationSummary
     */
    upperWhisker: any;
}
