/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The type of leaderboard. What the \"values\" represent.
 * @export
 * @enum {string}
 */
export enum LeaderboardCode {
    CompleteCount = 'complete_count',
    LargestUserPayout = 'largest_user_payout',
    SumUserPayout = 'sum_user_payout'
}

