/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface LeaderboardWinner
 */
export interface LeaderboardWinner {

    /**
     * The user's final rank in the leaderboard
     *
     * @type {any}
     * @memberof LeaderboardWinner
     */
    rank: any;

    /**
     * The time period range for the leaderboard.  Allowed values:   - __daily__ *(DAILY)*: UTC midnight to UTC midnight  - __weekly__ *(WEEKLY)*: Sunday Midnight to Sunday Midnight UTC  - __monthly__ *(MONTHLY)*: Jan 1 00:00:00
     *
     * @type {any}
     * @memberof LeaderboardWinner
     */
    freq: any;

    /**
     * The type of leaderboard. What the \"values\" represent.  Allowed values:   - __complete_count__ *(COMPLETE_COUNT)*: Number of Completes  - __largest_user_payout__ *(LARGEST_PAYOUT)*: Largest Single Payout  - __sum_user_payout__ *(SUM_PAYOUTS)*: (Sum of) Total Payouts
     *
     * @type {any}
     * @memberof LeaderboardWinner
     */
    boardCode: any;

    /**
     * The country this leaderboard is for.
     *
     * @type {any}
     * @memberof LeaderboardWinner
     */
    countryIso: any;

    /**
     * When the prize was issued.
     *
     * @type {any}
     * @memberof LeaderboardWinner
     */
    issued: any;

    /**
     * product_user_id
     *
     * @type {any}
     * @memberof LeaderboardWinner
     */
    bpuid: any;

    /**
     * @type {any}
     * @memberof LeaderboardWinner
     */
    description: any;

    /**
     * (USD cents) The reward amount
     *
     * @type {any}
     * @memberof LeaderboardWinner
     */
    amount: any;

    /**
     * The amount as a formatted string in USD. Can be displayed to the user.
     *
     * @type {any}
     * @memberof LeaderboardWinner
     */
    amountStr: any;

    /**
     * When the leaderboard started
     *
     * @type {any}
     * @memberof LeaderboardWinner
     */
    contestStart: any;

    /**
     * When the leaderboard ended
     *
     * @type {any}
     * @memberof LeaderboardWinner
     */
    contestEnd: any;
}
