/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface LeaderboardRow
 */
export interface LeaderboardRow {

    /**
     * product_user_id
     *
     * @type {any}
     * @memberof LeaderboardRow
     */
    bpuid: any;

    /**
     * The numerical data ranks (1 through n) of the values. Ties are ranked using the lowest rank in the group.
     *
     * @type {any}
     * @memberof LeaderboardRow
     */
    rank: any;

    /**
     * The value. The meaning of the value is dependent on the LeaderboardCode.
     *
     * @type {any}
     * @memberof LeaderboardRow
     */
    value: any;
}
