/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * A leaderboard exists independently for each product_id in each country. Each country is associated with a single timezone. There is a daily, weekly, and monthly leaderboard.
 *
 * @export
 * @interface Leaderboard
 */
export interface Leaderboard {

    /**
     * Unique ID for this leaderboard
     *
     * @type {any}
     * @memberof Leaderboard
     */
    id: any;

    /**
     * Descriptive name for the leaderboard based on the board_code
     *
     * @type {any}
     * @memberof Leaderboard
     */
    name: any;

    /**
     * The type of leaderboard. What the \"values\" represent.  Allowed values:   - __complete_count__ *(COMPLETE_COUNT)*: Number of Completes  - __largest_user_payout__ *(LARGEST_PAYOUT)*: Largest Single Payout  - __sum_user_payout__ *(SUM_PAYOUTS)*: (Sum of) Total Payouts
     *
     * @type {any}
     * @memberof Leaderboard
     */
    boardCode: any;

    /**
     * product_id
     *
     * @type {any}
     * @memberof Leaderboard
     */
    bpid: any;

    /**
     * The country this leaderboard is for.
     *
     * @type {any}
     * @memberof Leaderboard
     */
    countryIso: any;

    /**
     * The time period range for the leaderboard.  Allowed values:   - __daily__ *(DAILY)*: UTC midnight to UTC midnight  - __weekly__ *(WEEKLY)*: Sunday Midnight to Sunday Midnight UTC  - __monthly__ *(MONTHLY)*: Jan 1 00:00:00
     *
     * @type {any}
     * @memberof Leaderboard
     */
    freq: any;

    /**
     * (unix timestamp) The time it is right now
     *
     * @type {any}
     * @memberof Leaderboard
     */
    nowTimestamp: any;

    /**
     * The time it is right now (local time, in the leaderboard's timezone).
     *
     * @type {any}
     * @memberof Leaderboard
     */
    localTime: any;

    /**
     * (unix timestamp) The timestamp of the leaderboard. This is the UTC timestamp of the start of the leaderboard.
     *
     * @type {any}
     * @memberof Leaderboard
     */
    timestamp: any;

    /**
     * (unix timestamp) The start time of the time range this leaderboard covers.
     *
     * @type {any}
     * @memberof Leaderboard
     */
    startTimestamp: any;

    /**
     * (unix timestamp) The end time of the time range this leaderboard covers.
     *
     * @type {any}
     * @memberof Leaderboard
     */
    endTimestamp: any;

    /**
     * The start time of the time range this leaderboard covers (local time, in the leaderboard's timezone).
     *
     * @type {any}
     * @memberof Leaderboard
     */
    localStartTime: any;

    /**
     * The end time of the time range this leaderboard covers (local time, in the leaderboard's timezone).
     *
     * @type {any}
     * @memberof Leaderboard
     */
    localEndTime: any;

    /**
     * A formatted string for time range covered by this leaderboard. Can be used to display to users.
     *
     * @type {any}
     * @memberof Leaderboard
     */
    startEndStr: any;

    /**
     * The timezone for the requested country
     *
     * @type {any}
     * @memberof Leaderboard
     */
    timezoneName: any;

    /**
     * The UTC offset for the timezone
     *
     * @type {any}
     * @memberof Leaderboard
     */
    utcOffset: any;

    /**
     * @type {any}
     * @memberof Leaderboard
     */
    sortOrder?: any;

    /**
     * The total number of rows in the leaderboard.
     *
     * @type {any}
     * @memberof Leaderboard
     */
    rowCount: any;

    /**
     * @type {any}
     * @memberof Leaderboard
     */
    rows?: any;
}
