/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MarketplaceSummary
 */
export interface MarketplaceSummary {

    /**
     * Inventory of the marketplace
     *
     * @type {any}
     * @memberof MarketplaceSummary
     */
    inventory: any;

    /**
     * User activity of the marketplace
     *
     * @type {any}
     * @memberof MarketplaceSummary
     */
    userActivity?: any;
}
