/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MarketplaceInventorySummary
 */
export interface MarketplaceInventorySummary {

    /**
     * The count of tasks that are currently live
     *
     * @type {any}
     * @memberof MarketplaceInventorySummary
     */
    liveTasks?: any;

    /**
     * The count of gen-pop tasks that are currently live
     *
     * @type {any}
     * @memberof MarketplaceInventorySummary
     */
    liveGenPopTasks?: any;

    /**
     * The count of tasks created
     *
     * @type {any}
     * @memberof MarketplaceInventorySummary
     */
    tasksCreated?: any;

    /**
     * Number of finishes needed across all live tasks
     *
     * @type {any}
     * @memberof MarketplaceInventorySummary
     */
    requiredFinishes?: any;

    /**
     * The distribution of payouts for all live tasks
     *
     * @type {any}
     * @memberof MarketplaceInventorySummary
     */
    payout?: any;

    /**
     * The distribution of expected durations for all live tasks
     *
     * @type {any}
     * @memberof MarketplaceInventorySummary
     */
    expectedDuration?: any;

    /**
     * The distribution of required finishes on all live tasks
     *
     * @type {any}
     * @memberof MarketplaceInventorySummary
     */
    requiredFinishesPerTask?: any;
}
