/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MarketplaceOfferwall } from './marketplace-offerwall';
import { OfferWallInfo } from './offer-wall-info';
 /**
 * 
 *
 * @export
 * @interface MarketplaceOfferwallResponse
 */
export interface MarketplaceOfferwallResponse {

    /**
     * @type {OfferWallInfo}
     * @memberof MarketplaceOfferwallResponse
     */
    info: OfferWallInfo;

    /**
     * @type {MarketplaceOfferwall}
     * @memberof MarketplaceOfferwallResponse
     */
    offerwall: MarketplaceOfferwall;
}
