/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PatternValidation
 */
export interface PatternValidation {

    /**
     * Message to display if validation fails
     *
     * @type {any}
     * @memberof PatternValidation
     */
    message: any;

    /**
     * Regex string to validate. min_length and max_length are checked separately, even if they are part of the regex.
     *
     * @type {any}
     * @memberof PatternValidation
     */
    pattern: any;
}
