/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The method in which the requested payout is delivered.
 * @export
 * @enum {string}
 */
export enum PayoutType {
    PAYPAL = 'PAYPAL',
    TANGO = 'TANGO',
    Dwolla = 'dwolla',
    ACH = 'ACH',
    CASHINMAIL = 'CASH_IN_MAIL',
    PRIZE = 'PRIZE',
    AMT = 'AMT',
    AmtBonus = 'amt_bonus',
    AmtAssignment = 'amt_assignment'
}

