/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Payouts are in Integer USD Cents
 *
 * @export
 * @interface PayoutSummary
 */
export interface PayoutSummary {

    /**
     * @type {any}
     * @memberof PayoutSummary
     */
    min: any;

    /**
     * @type {any}
     * @memberof PayoutSummary
     */
    max: any;

    /**
     * @type {any}
     * @memberof PayoutSummary
     */
    mean?: any;

    /**
     * @type {any}
     * @memberof PayoutSummary
     */
    q1: any;

    /**
     * @type {any}
     * @memberof PayoutSummary
     */
    q2: any;

    /**
     * @type {any}
     * @memberof PayoutSummary
     */
    q3: any;

    /**
     * @type {any}
     * @memberof PayoutSummary
     */
    lowerWhisker: any;

    /**
     * @type {any}
     * @memberof PayoutSummary
     */
    upperWhisker: any;
}
