/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PaypalCashoutMethodData
 */
export interface PaypalCashoutMethodData {

    /**
     * @type {any}
     * @memberof PaypalCashoutMethodData
     */
    type?: any;

    /**
     * Email address of the paypal user
     *
     * @type {any}
     * @memberof PaypalCashoutMethodData
     */
    email: any;
}
