/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ProfilingInfoResponse
 */
export interface ProfilingInfoResponse {

    /**
     * The status of the API response.
     *
     * @type {any}
     * @memberof ProfilingInfoResponse
     */
    status: any;

    /**
     * An optional message, if the status is error.
     *
     * @type {any}
     * @memberof ProfilingInfoResponse
     */
    msg?: any;

    /**
     * @type {any}
     * @memberof ProfilingInfoResponse
     */
    profilingInfo: any;
}
