/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface QuestionInfo
 */
export interface QuestionInfo {

    /**
     * @type {any}
     * @memberof QuestionInfo
     */
    propertyId: any;

    /**
     * @type {any}
     * @memberof QuestionInfo
     */
    propertyLabel: any;

    /**
     *  Allowed values:   - __i__ *(UPK_ITEM)*: UserProfileKnowledge Item  - __n__ *(UPK_NUMERICAL)*: UserProfileKnowledge Numerical  - __x__ *(UPK_TEXT)*: UserProfileKnowledge Text
     *
     * @type {any}
     * @memberof QuestionInfo
     */
    propType?: any;

    /**
     *  Allowed values:   - __*__ *(ZERO_OR_MORE)*: Zero or More  - __?__ *(ZERO_OR_ONE)*: Zero or One
     *
     * @type {any}
     * @memberof QuestionInfo
     */
    cardinality?: any;

    /**
     * @type {any}
     * @memberof QuestionInfo
     */
    countryIso: any;

    /**
     * A Gold-Standard question has been enumerated for all possible values (per country) as best as possible by GRL,allowing it to be mapped across inventory sources. A property not marked as Gold-Standard may have: 1) marketplace qid associations & 2) category associations, but doesn't have a defined 'range' (list of allowed itemsin a multiple choice question). This is used for exposing a user's profiling data & forthe Nudge API.
     *
     * @type {any}
     * @memberof QuestionInfo
     */
    goldStandard?: any;

    /**
     * @type {any}
     * @memberof QuestionInfo
     */
    options?: any;

    /**
     * @type {any}
     * @memberof QuestionInfo
     */
    category: any;
}
