/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ReportTask
 */
export interface ReportTask {

    /**
     * The unique identifier for the user, which is set by the Supplier.
     *
     * @type {any}
     * @memberof ReportTask
     */
    bpuid: any;

    /**
     * The reason a user reported a task.  Allowed values:   - __0__ *(REASON_UNKNOWN)*: Used to indicate the user exited the task without giving feedback  - __1__ *(TECHNICAL_ERROR)*: Task is in the wrong language/country, unanswerable question, won't proceed to next question, loading forever, error message  - __2__ *(NO_REDIRECT)*: Task ended (completed or failed, and showed the user some dialog indicating the task was over), but failed to redirect  - __3__ *(PRIVACY_INVASION)*: Asked for full name, home address, identity on another site, cc  - __4__ *(UNCOMFORTABLE_TOPICS)*: Asked about children, employer, medical issues, drug use, STDs, etc.  - __5__ *(ASKED_FOR_NOT_ALLOWED_ACTION)*: Asked to install software, signup/login to external site, access webcam, promise to pay using external site, etc.  - __6__ *(BAD_ON_MOBILE)*: Task doesn't work well on a mobile device  - __7__ *(DIDNT_LIKE)*: Too long, too boring, confusing, complicated, too many open-ended/free-response questions
     *
     * @type {any}
     * @memberof ReportTask
     */
    reasons?: any;

    /**
     * @type {any}
     * @memberof ReportTask
     */
    notes?: any;
}
