/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SingleEntryBucket
 */
export interface SingleEntryBucket {

    /**
     * Unique identifier this particular bucket
     *
     * @type {any}
     * @memberof SingleEntryBucket
     */
    id: any;

    /**
     * The URL to send a respondent into. Must not edit this URL in any way
     *
     * @type {any}
     * @memberof SingleEntryBucket
     */
    uri: any;
}
