/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Only returns a single bucket with the top scoring tasks.  Offerwall code: `5fl8bpv5`
 *
 * @export
 * @interface SingleEntryOfferWall
 */
export interface SingleEntryOfferWall {

    /**
     * Unique identifier to reference a generated offerwall
     *
     * @type {any}
     * @memberof SingleEntryOfferWall
     */
    id: any;

    /**
     * Total opportunities available for specific bpuid respondent and parameters. This value changes frequently and can be used to determine if a respondent has potential tasks available, regardless of the offerwall type being requested. If the value is 0, no buckets will be generated.
     *
     * @type {any}
     * @memberof SingleEntryOfferWall
     */
    availabilityCount: any;

    /**
     * @type {any}
     * @memberof SingleEntryOfferWall
     */
    buckets?: any;

    /**
     *  The format describing the str representation of a payout. Typically, this would be displayed to a user. The payout_format is similar to python format string with a subset of functionality supported. Only float with a precision are supported along with an optional comma for a thousands separator. In addition, a mathematical operator can be applied, such as dividing by 100.  Examples are shown assuming payout = 100 (one dollar). - \"{payout*10:,.0f} Points\" -> \"1,000 Points\" - \"${payout/100:.2f}\" -> \"$1.00\" 
     *
     * @type {any}
     * @memberof SingleEntryOfferWall
     */
    payoutFormat: any;
}
