/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * This offerwall contains tasks for which the user has a conditional eligibility. The questions that a user must answer to determine the eligibility are included within each bucket. Additionally, the question definitions are included for convenience.  Offerwall code: `37d1da64`
 *
 * @export
 * @interface SoftPairOfferwall
 */
export interface SoftPairOfferwall {

    /**
     * Unique identifier to reference a generated offerwall
     *
     * @type {any}
     * @memberof SoftPairOfferwall
     */
    id: any;

    /**
     * Total opportunities available for specific bpuid respondent and parameters. This value changes frequently and can be used to determine if a respondent has potential tasks available, regardless of the offerwall type being requested. If the value is 0, no buckets will be generated.
     *
     * @type {any}
     * @memberof SoftPairOfferwall
     */
    availabilityCount: any;

    /**
     * @type {any}
     * @memberof SoftPairOfferwall
     */
    buckets?: any;

    /**
     * @type {any}
     * @memberof SoftPairOfferwall
     */
    questionInfo?: any;
}
