/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SoftPairBucket
 */
export interface SoftPairBucket {

    /**
     * Unique identifier this particular bucket
     *
     * @type {any}
     * @memberof SoftPairBucket
     */
    id: any;

    /**
     * The URL to send a respondent into. Must not edit this URL in any way. If the eligibility is conditional or ineligible, the uri will be null.
     *
     * @type {any}
     * @memberof SoftPairBucket
     */
    uri: any;

    /**
     * @type {any}
     * @memberof SoftPairBucket
     */
    category?: any;

    /**
     * @type {any}
     * @memberof SoftPairBucket
     */
    contents: any;

    /**
     * @type {any}
     * @memberof SoftPairBucket
     */
    eligibility: any;

    /**
     * @type {any}
     * @memberof SoftPairBucket
     */
    missingQuestions?: any;

    /**
     * this is the max loi of the contents
     *
     * @type {any}
     * @memberof SoftPairBucket
     */
    loi: any;

    /**
     * this is the min payout of the contents
     *
     * @type {any}
     * @memberof SoftPairBucket
     */
    payout: any;
}
