/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OfferWallInfo } from './offer-wall-info';
import { SoftPairOfferwall } from './soft-pair-offerwall';
 /**
 * 
 *
 * @export
 * @interface SoftPairOfferwallResponse
 */
export interface SoftPairOfferwallResponse {

    /**
     * @type {OfferWallInfo}
     * @memberof SoftPairOfferwallResponse
     */
    info: OfferWallInfo;

    /**
     * @type {SoftPairOfferwall}
     * @memberof SoftPairOfferwallResponse
     */
    offerwall: SoftPairOfferwall;
}
