/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum Source {
    G = 'g',
    C = 'c',
    A = 'a',
    D = 'd',
    Et = 'et',
    F = 'f',
    I = 'i',
    L = 'l',
    M = 'm',
    N = 'n',
    O = 'o',
    E = 'e',
    R = 'r',
    Pr = 'pr',
    P = 'p',
    Rd = 'rd',
    H = 'h',
    S = 's',
    T = 't',
    U = 'u',
    W = 'w'
}

