/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StatusSuccessFail } from './status-success-fail';
 /**
 * 
 *
 * @export
 * @interface StatusInfoResponseFail
 */
export interface StatusInfoResponseFail {

    /**
     * @type {StatusSuccessFail}
     * @memberof StatusInfoResponseFail
     */
    info: StatusSuccessFail;

    /**
     * An optional message, if success is False
     *
     * @type {any}
     * @memberof StatusInfoResponseFail
     */
    msg: any;
}
