/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TangoCashoutMethodData
 */
export interface TangoCashoutMethodData {

    /**
     * @type {any}
     * @memberof TangoCashoutMethodData
     */
    type?: any;

    /**
     * tango utid
     *
     * @type {any}
     * @memberof TangoCashoutMethodData
     */
    utid: any;

    /**
     * @type {any}
     * @memberof TangoCashoutMethodData
     */
    countries: any;

    /**
     * @type {any}
     * @memberof TangoCashoutMethodData
     */
    valueType: any;
}
