/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DurationSummary } from './duration-summary';
import { PayoutSummary } from './payout-summary';
 /**
 * 
 *
 * @export
 * @interface TopNPlusRecontactBucket
 */
export interface TopNPlusRecontactBucket {

    /**
     * Unique identifier this particular bucket
     *
     * @type {any}
     * @memberof TopNPlusRecontactBucket
     */
    id: any;

    /**
     * The URL to send a respondent into. Must not edit this URL in any way
     *
     * @type {any}
     * @memberof TopNPlusRecontactBucket
     */
    uri: any;

    /**
     * For UI. Provides a dimensionality position for the bucket on the x-axis.
     *
     * @type {any}
     * @memberof TopNPlusRecontactBucket
     */
    x?: any;

    /**
     * For UI. Provides a dimensionality position for the bucket on the y-axis.
     *
     * @type {any}
     * @memberof TopNPlusRecontactBucket
     */
    y?: any;

    /**
     * Currently unused. Will always return empty string
     *
     * @type {any}
     * @memberof TopNPlusRecontactBucket
     */
    name?: any;

    /**
     * Currently unused. Will always return empty string
     *
     * @type {any}
     * @memberof TopNPlusRecontactBucket
     */
    description?: any;

    /**
     * @type {any}
     * @memberof TopNPlusRecontactBucket
     */
    category?: any;

    /**
     * @type {any}
     * @memberof TopNPlusRecontactBucket
     */
    contents: any;

    /**
     * @type {DurationSummary}
     * @memberof TopNPlusRecontactBucket
     */
    duration: DurationSummary;

    /**
     * @type {PayoutSummary}
     * @memberof TopNPlusRecontactBucket
     */
    payout: PayoutSummary;

    /**
     * @type {any}
     * @memberof TopNPlusRecontactBucket
     */
    qualityScore: any;

    /**
     * @type {any}
     * @memberof TopNPlusRecontactBucket
     */
    isRecontact: any;

    /**
     * This will always be 'USD'
     *
     * @type {any}
     * @memberof TopNPlusRecontactBucket
     */
    currency?: any;
}
