/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Same as the TopNOfferWall, but the buckets include contents.  Offerwall code: `b145b803`
 *
 * @export
 * @interface TopNPlusOfferWall
 */
export interface TopNPlusOfferWall {

    /**
     * Unique identifier to reference a generated offerwall
     *
     * @type {any}
     * @memberof TopNPlusOfferWall
     */
    id: any;

    /**
     * Total opportunities available for specific bpuid respondent and parameters. This value changes frequently and can be used to determine if a respondent has potential tasks available, regardless of the offerwall type being requested. If the value is 0, no buckets will be generated.
     *
     * @type {any}
     * @memberof TopNPlusOfferWall
     */
    availabilityCount: any;

    /**
     * @type {any}
     * @memberof TopNPlusOfferWall
     */
    buckets?: any;
}
