/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpkQuestionConfigurationTE
 */
export interface UpkQuestionConfigurationTE {

    /**
     * Maximum str length of any input. Meant as an easy, nonregex based check.
     *
     * @type {any}
     * @memberof UpkQuestionConfigurationTE
     */
    maxLength?: any;

    /**
     * Minimum str length of any input. Meant as an easy, nonregex based check.
     *
     * @type {any}
     * @memberof UpkQuestionConfigurationTE
     */
    minLength?: any;
}
