/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UpkQuestionType } from './upk-question-type';
 /**
 * 
 *
 * @export
 * @interface UpkQuestionOut
 */
export interface UpkQuestionOut {

    /**
     * @type {any}
     * @memberof UpkQuestionOut
     */
    questionId?: any;

    /**
     * what marketplace question this question links to
     *
     * @type {any}
     * @memberof UpkQuestionOut
     */
    extQuestionId?: any;

    /**
     * @type {UpkQuestionType}
     * @memberof UpkQuestionOut
     */
    questionType: UpkQuestionType;

    /**
     * @type {any}
     * @memberof UpkQuestionOut
     */
    countryIso: any;

    /**
     * @type {any}
     * @memberof UpkQuestionOut
     */
    languageIso: any;

    /**
     * The text shown to respondents
     *
     * @type {any}
     * @memberof UpkQuestionOut
     */
    questionText: any;

    /**
     * @type {any}
     * @memberof UpkQuestionOut
     */
    choices?: any;

    /**
     * @type {any}
     * @memberof UpkQuestionOut
     */
    selector?: any;

    /**
     * @type {any}
     * @memberof UpkQuestionOut
     */
    configuration?: any;

    /**
     * @type {any}
     * @memberof UpkQuestionOut
     */
    validation?: any;

    /**
     * The number of live Tasks that use this UPK Question
     *
     * @type {any}
     * @memberof UpkQuestionOut
     */
    taskCount?: any;

    /**
     * GRL's internal ranked score for the UPK Question
     *
     * @type {any}
     * @memberof UpkQuestionOut
     */
    taskScore?: any;

    /**
     * @type {any}
     * @memberof UpkQuestionOut
     */
    p?: any;
}
