/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpkQuestionChoice
 */
export interface UpkQuestionChoice {

    /**
     * The unique identifier for a response to a qualification
     *
     * @type {any}
     * @memberof UpkQuestionChoice
     */
    choiceId: any;

    /**
     * The response text shown to respondents
     *
     * @type {any}
     * @memberof UpkQuestionChoice
     */
    choiceText: any;

    /**
     * @type {any}
     * @memberof UpkQuestionChoice
     */
    order: any;

    /**
     * @type {any}
     * @memberof UpkQuestionChoice
     */
    group?: any;

    /**
     * If answer is exclusive, it can be the only option selected
     *
     * @type {any}
     * @memberof UpkQuestionChoice
     */
    exclusive?: any;

    /**
     * @type {any}
     * @memberof UpkQuestionChoice
     */
    importance?: any;
}
