/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpkQuestionResponse
 */
export interface UpkQuestionResponse {

    /**
     * The status of the API response.
     *
     * @type {any}
     * @memberof UpkQuestionResponse
     */
    status: any;

    /**
     * An optional message, if the status is error.
     *
     * @type {any}
     * @memberof UpkQuestionResponse
     */
    msg?: any;

    /**
     * @type {any}
     * @memberof UpkQuestionResponse
     */
    questions: any;

    /**
     * For internal use
     *
     * @type {any}
     * @memberof UpkQuestionResponse
     */
    consentQuestions?: any;

    /**
     * For internal use
     *
     * @type {any}
     * @memberof UpkQuestionResponse
     */
    specialQuestions?: any;

    /**
     * The number of questions returned
     *
     * @type {any}
     * @memberof UpkQuestionResponse
     */
    count: any;
}
