/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface USDeliveryAddress
 */
export interface USDeliveryAddress {

    /**
     * @type {any}
     * @memberof USDeliveryAddress
     */
    nameOrAttn: any;

    /**
     * @type {any}
     * @memberof USDeliveryAddress
     */
    company?: any;

    /**
     * @type {any}
     * @memberof USDeliveryAddress
     */
    phoneNumber?: any;

    /**
     * @type {any}
     * @memberof USDeliveryAddress
     */
    address: any;

    /**
     * @type {any}
     * @memberof USDeliveryAddress
     */
    city: any;

    /**
     * @type {any}
     * @memberof USDeliveryAddress
     */
    state: any;

    /**
     * @type {any}
     * @memberof USDeliveryAddress
     */
    postalCode: any;

    /**
     * @type {any}
     * @memberof USDeliveryAddress
     */
    country?: any;
}
