/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UserWalletBalance
 */
export interface UserWalletBalance {

    /**
     * (USD cents) The amount in the user's wallet.
     *
     * @type {any}
     * @memberof UserWalletBalance
     */
    amount: any;

    /**
     * (USD cents) The amount in the user's wallet this is currently redeemable.
     *
     * @type {any}
     * @memberof UserWalletBalance
     */
    redeemableAmount: any;

    /**
     *  The format describing the str representation of a payout. Typically, this would be displayed to a user. The payout_format is similar to python format string with a subset of functionality supported. Only float with a precision are supported along with an optional comma for a thousands separator. In addition, a mathematical operator can be applied, such as dividing by 100.  Examples are shown assuming payout = 100 (one dollar). - \"{payout*10:,.0f} Points\" -> \"1,000 Points\" - \"${payout/100:.2f}\" -> \"$1.00\" 
     *
     * @type {any}
     * @memberof UserWalletBalance
     */
    payoutFormat: any;

    /**
     * The 'amount' with the payout_format applied. Can be displayed to the user.
     *
     * @type {any}
     * @memberof UserWalletBalance
     */
    amountString: any;

    /**
     * The 'redeemable_amount' with the payout_format applied. Can be displayed to the user.
     *
     * @type {any}
     * @memberof UserWalletBalance
     */
    redeemableAmountString: any;
}
