/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Stores configuration for the user wallet handling
 *
 * @export
 * @interface UserWalletConfig
 */
export interface UserWalletConfig {

    /**
     * If enabled, the users' wallets are managed.
     *
     * @type {any}
     * @memberof UserWalletConfig
     */
    enabled?: any;

    /**
     * Uses Amazon Mechanical Turk
     *
     * @type {any}
     * @memberof UserWalletConfig
     */
    amt?: any;

    /**
     * @type {any}
     * @memberof UserWalletConfig
     */
    supportedPayoutTypes?: any;

    /**
     * Minimum cashout amount. If enabled is True and no min_cashout is set, will default to $0.01.
     *
     * @type {any}
     * @memberof UserWalletConfig
     */
    minCashout?: any;
}
