/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UserProfileKnowledge
 */
export interface UserProfileKnowledge {

    /**
     * @type {any}
     * @memberof UserProfileKnowledge
     */
    propertyId: any;

    /**
     * @type {any}
     * @memberof UserProfileKnowledge
     */
    propertyLabel: any;

    /**
     * @type {any}
     * @memberof UserProfileKnowledge
     */
    translation: any;

    /**
     * @type {any}
     * @memberof UserProfileKnowledge
     */
    answer?: any;

    /**
     * When the User submitted this Profiling data
     *
     * @type {any}
     * @memberof UserProfileKnowledge
     */
    created: any;
}
