/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UserWalletBalance } from './user-wallet-balance';
 /**
 * 
 *
 * @export
 * @interface UserWalletBalanceResponse
 */
export interface UserWalletBalanceResponse {

    /**
     * The status of the API response.
     *
     * @type {any}
     * @memberof UserWalletBalanceResponse
     */
    status: any;

    /**
     * An optional message, if the status is error.
     *
     * @type {any}
     * @memberof UserWalletBalanceResponse
     */
    msg?: any;

    /**
     * @type {UserWalletBalance}
     * @memberof UserWalletBalanceResponse
     */
    wallet: UserWalletBalance;
}
