/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Send the answers to one or more questions for a user. A question is uniquely specified by the question_id key. The answer is: the choice_id if the question_type is \"MC\" the actual entered text if the question_type is \"TE\"  TODO: look up the question_type from the question_id to apply MC or     TE specific validation on the answer(s)
 *
 * @export
 * @interface UserQuestionAnswerIn
 */
export interface UserQuestionAnswerIn {

    /**
     * @type {any}
     * @memberof UserQuestionAnswerIn
     */
    questionId: any;

    /**
     * The user's answers to this question. Must pass the choice_id if the question is a Multiple Choice, or the actual text if the question is Text Entry
     *
     * @type {any}
     * @memberof UserQuestionAnswerIn
     */
    answer: any;
}
