/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UserProfileKnowledgeAnswer
 */
export interface UserProfileKnowledgeAnswer {

    /**
     * @type {any}
     * @memberof UserProfileKnowledgeAnswer
     */
    id?: any;

    /**
     * @type {any}
     * @memberof UserProfileKnowledgeAnswer
     */
    label?: any;

    /**
     * @type {any}
     * @memberof UserProfileKnowledgeAnswer
     */
    translation?: any;

    /**
     * @type {any}
     * @memberof UserProfileKnowledgeAnswer
     */
    value?: any;
}
