/* tslint:disable */
/* eslint-disable */
/**
 * General Research Full Service Brokerage API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OfferWallInfo } from './offer-wall-info';
import { WXETOfferwall } from './wxetofferwall';
 /**
 * 
 *
 * @export
 * @interface WXETOfferwallResponse
 */
export interface WXETOfferwallResponse {

    /**
     * @type {OfferWallInfo}
     * @memberof WXETOfferwallResponse
     */
    info: OfferWallInfo;

    /**
     * @type {WXETOfferwall}
     * @memberof WXETOfferwallResponse
     */
    offerwall: WXETOfferwall;
}
